@startuml

box "Consuming Service"
participant Consumer as "Event Consumer"
end box

box "AAS Service"
participant Feed as "Event Feed"
end box

activate Consumer
Consumer -> Feed : GetAllEvents(globalAssetId, type, limit)
activate Feed
Consumer <-- Feed : Result (events 1..n, paging_metadata.cursor)
deactivate Feed

loop while paging_metadata contains a cursor
  Consumer -> Feed : GetAllEvents(cursor)
  activate Feed
  Consumer <-- Feed : Result (next events, optional cursor)
  deactivate Feed
end

Consumer -> Consumer : process events,\nremember id of last processed event

...later...

Consumer -> Feed : GetAllEvents(globalAssetId, type, lastEventId)
activate Feed
Consumer <-- Feed : Result (events published after lastEventId)
deactivate Feed

deactivate Consumer

@enduml
