////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/).

SPDX-License-Identifier: CC-BY-4.0

////

:mm: https://industrialdigitaltwin.io/aas-specifications/IDTA-01001/v3.2

[#eventing]
= Eventing

[#eventing-general]
== General

Eventing enables clients to react to modifications of Asset Administration Shells, Submodels, SubmodelElements, Concept Descriptions, and of the link between assets and Asset Administration Shells.
A service provides an _event_ for every modification of the content it provides.
An event states which object was modified, how, and when, and it contains the modified object or a Reference to it.
Typical use cases are:

* informing customers about a new record in a Submodel with Product Change Notifications of a supplier,
* keeping replicas, caches, and search indexes consistent with a repository,
* observing individual values, e.g. a measured temperature,
* detecting that an Asset Administration Shell for an asset has become available or has been replaced.

Events are represented according to CloudEvents xref:bibliography.adoc#bib16[[16\]] in the JSON event format xref:bibliography.adoc#bib17[[17\]].
This chapter defines the events, the modifications that result in events, event profiles, and the operation _GetAllEvents_ for retrieving events.

[#eventing-event]
== Event

[#eventing-event-structure]
=== Event Structure

<<fig-eventing-event-data>> shows the class _Event_ and the classes of its data.
The attributes of _Event_ are the CloudEvents context attributes and the data; CloudEvents extension attributes are not used.

.Event and event data
[[fig-eventing-event-data]]
[plantuml, eventing-event-data, svg]
....
include::partial$diagrams/eventing-event-data.puml[]
....

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class Name 3+e|[[Event]]Event
h|Explanation 3+a|Modification of the content provided by a service, serialized as CloudEvent in the JSON event format.

This class is not part of the metamodel.
h|Inherits from 3+|--
h|semanticId 3+|`\https://admin-shell.io/aas/API/DataTypes/Event/3/3`

h|Attribute h|Explanation h|Type h|Card.
e|specversion a|CloudEvents version; value `1.0` |string |1
e|id a|Identifier of the event, unique within the scope of `source`, e.g. a UUID xref:bibliography.adoc#bib19[[19\]] |string |1
e|source a|Collection containing the modified object, see <<eventing-source-subject>> |string (URI-reference) |1
e|subject a|Modified object within `source`, see <<eventing-source-subject>> |string |1
e|type a|Event type, see <<eventing-event-types>> |string |1
e|time a|Point in time at which the modification became effective |link:{mm}/spec-metamodel/datatypes.html#DateTimeUtc[DateTimeUtc] |1
e|datacontenttype a|Value `application/json` |string |1
e|dataschema a|Identifier of the class and Content of `data`, see <<eventing-data-schemas>> |string (URI) |1
e|data a|Data of the event |xref:EventData[EventData] |1
|===

The following rules apply:

. All events resulting from the same modification shall have the same `time`.
. An event with a given `source` and `id` shall always have the same content.

[#eventing-source-subject]
=== Source and Subject

The `source` of an event is the URL of the collection resource that contains the modified object in the HTTP/REST API, and the `subject` is the identification of the object within this collection.
The `subject` is not encoded.
Appending "/" and the encoded subject to the `source` results in the URL of the modified object, with the encoding defined in xref:http-rest-api/http-rest-api.adoc#design-decisions[Design Decisions].

.Source and subject
[%autowidth,width="100%",cols="20%,45%,35%",options="header",]
|===
|Events of |source |subject
e|AssetAdministrationShell |`\{base}/shells` |Identifier of the Asset Administration Shell
e|Submodel |`\{base}/submodels` |Identifier of the Submodel
e|SubmodelElement |`\{base}/submodels/\{submodelIdentifier}/submodel-elements` |link:{mm}/mappings/mappings.html#_format_path_idshortpath_serialization_in_json[idShortPath] of the SubmodelElement
e|ConceptDescription |`\{base}/concept-descriptions` |Identifier of the Concept Description
e|Asset |`\{base}/lookup/shells` |link:{mm}/spec-metamodel/core.html#globalAssetId[globalAssetId] of the asset
|===

`\{base}` is the base URL of the HTTP/REST API of the service.
The `source` does not depend on the path used for the modification; e.g. a Submodel modified via `/shells/\{aasIdentifier}/submodels/\{submodelIdentifier}` has the `source` `\{base}/submodels`.
For asset events, the resulting URL is not a resource; the Asset Administration Shells of an asset are returned by
xref:specification/interfaces.adoc#GetAllAssetAdministrationShellIdsByAssetLink[GetAllAssetAdministrationShellIdsByAssetLink].

[#eventing-event-types]
=== Event Types

The `type` of an event has the form `io.admin-shell.<object>.<modification>.v1` with the values of <<table-eventing-event-types>>.

[[table-eventing-event-types]]
.Event types
[%autowidth,width="100%",cols="22%,28%,50%",options="header",]
|===
|<object> |<modification> |data
|`aas` |`created`, `updated`, `deleted` |xref:AssetAdministrationShellEventData[AssetAdministrationShellEventData]
|`submodel` |`created`, `updated`, `deleted` |xref:SubmodelEventData[SubmodelEventData]
|`submodelelement` |`created`, `updated`, `deleted` |xref:SubmodelElementEventData[SubmodelElementEventData]
|`conceptdescription` |`created`, `updated`, `deleted` |xref:ConceptDescriptionEventData[ConceptDescriptionEventData]
|`asset` |`created`, `updated`, `deleted` |xref:AssetEventData[AssetEventData]
|===

Further event types may be defined by event profiles, see <<eventing-profiles>>.

[#eventing-event-data]
=== Event Data

The data of an event is provided with the xref:specification/interfaces-operation-parameters.adoc#enumeration-content[Content] _Normal_ or _Reference_.
With Content _Normal_, the data contains the modified object after the modification, and for _deleted_ events the object before the modification.
With Content _Reference_, the data contains a ModelReference to the modified object instead.
The other attributes of the data are identical for both Contents.

.Modified object in the event data
[%autowidth,width="100%",cols="30%,40%,30%",options="header",]
|===
|Event data |Content _Normal_ |Content _Reference_
e|AssetAdministrationShellEventData |AssetAdministrationShell |Reference
e|SubmodelEventData |Submodel with Content _Metadata_ |Reference
e|SubmodelElementEventData |SubmodelElement with Level _Deep_ and Extent _WithoutBLOBValue_ |Reference
e|ConceptDescriptionEventData |ConceptDescription |Reference
e|AssetEventData |References to the linked Asset Administration Shells |not present
|===

A ModelReference to a Submodel or SubmodelElement in the data shall contain `referredSemanticId` if the referenced object has a _semanticId_.
This does not apply to References that are part of a serialized AssetAdministrationShell, Submodel, or SubmodelElement.

The `globalAssetIds` of Submodel and SubmodelElement events are the _globalAssetIds_ of all Asset Administration Shells provided by the same service that reference the Submodel at the time of the modification.
Changes of these references result in AAS events, not in Submodel events.

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class Name 3+e|[[EventData]]EventData \<<abstract>>
h|Explanation 3+a|Data of an event.

This class is not part of the metamodel.
h|Inherits from 3+|--
h|semanticId 3+|`\https://admin-shell.io/aas/API/DataTypes/EventData/3/3`
h|Attribute h|Explanation h|Type h|Card.
4+|--
|===

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class Name 3+e|[[AssetAdministrationShellEventData]]AssetAdministrationShellEventData
h|Explanation 3+a|Data of an event of type `io.admin-shell.aas.<modification>.v1`.

This class is not part of the metamodel.
h|Inherits from 3+|xref:EventData[EventData]
h|semanticId 3+|`\https://admin-shell.io/aas/API/DataTypes/AssetAdministrationShellEventData/3/3`
h|Attribute h|Explanation h|Type h|Card.
e|globalAssetIds a|_globalAssetId_ of the Asset Administration Shell, if set; at most one entry |link:{mm}/spec-metamodel/datatypes.html#Identifier[Identifier] |0..*
e|assetAdministrationShell a|Asset Administration Shell (Content _Normal_) or ModelReference to it (Content _Reference_) |link:{mm}/spec-metamodel/core.html#AssetAdministrationShell[AssetAdministrationShell] or link:{mm}/spec-metamodel/referencing.html#Reference[Reference] |1
|===

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class Name 3+e|[[SubmodelEventData]]SubmodelEventData
h|Explanation 3+a|Data of an event of type `io.admin-shell.submodel.<modification>.v1`.

This class is not part of the metamodel.
h|Inherits from 3+|xref:EventData[EventData]
h|semanticId 3+|`\https://admin-shell.io/aas/API/DataTypes/SubmodelEventData/3/3`
h|Attribute h|Explanation h|Type h|Card.
e|globalAssetIds a|_globalAssetIds_ of the Asset Administration Shells referencing the Submodel |link:{mm}/spec-metamodel/datatypes.html#Identifier[Identifier] |0..*
e|submodel a|Submodel with Content _Metadata_ (Content _Normal_) or ModelReference to it (Content _Reference_) |link:{mm}/spec-metamodel/core.html#Submodel[Submodel] or link:{mm}/spec-metamodel/referencing.html#Reference[Reference] |1
|===

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class Name 3+e|[[SubmodelElementEventData]]SubmodelElementEventData
h|Explanation 3+a|Data of an event of type `io.admin-shell.submodelelement.<modification>.v1`.

This class is not part of the metamodel.
h|Inherits from 3+|xref:EventData[EventData]
h|semanticId 3+|`\https://admin-shell.io/aas/API/DataTypes/SubmodelElementEventData/3/3`
h|Attribute h|Explanation h|Type h|Card.
e|submodel a|ModelReference to the Submodel containing the SubmodelElement |link:{mm}/spec-metamodel/referencing.html#Reference[Reference] |1
e|globalAssetIds a|_globalAssetIds_ of the Asset Administration Shells referencing the Submodel |link:{mm}/spec-metamodel/datatypes.html#Identifier[Identifier] |0..*
e|submodelElement a|SubmodelElement (Content _Normal_) or ModelReference to it (Content _Reference_) |link:{mm}/spec-metamodel/core.html#SubmodelElement[SubmodelElement] or link:{mm}/spec-metamodel/referencing.html#Reference[Reference] |1
|===

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class Name 3+e|[[ConceptDescriptionEventData]]ConceptDescriptionEventData
h|Explanation 3+a|Data of an event of type `io.admin-shell.conceptdescription.<modification>.v1`.

This class is not part of the metamodel.
h|Inherits from 3+|xref:EventData[EventData]
h|semanticId 3+|`\https://admin-shell.io/aas/API/DataTypes/ConceptDescriptionEventData/3/3`
h|Attribute h|Explanation h|Type h|Card.
e|conceptDescription a|Concept Description (Content _Normal_) or ModelReference to it (Content _Reference_) |link:{mm}/spec-metamodel/concept-description.html#ConceptDescription[ConceptDescription] or link:{mm}/spec-metamodel/referencing.html#Reference[Reference] |1
|===

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class Name 3+e|[[AssetEventData]]AssetEventData
h|Explanation 3+a|Data of an event of type `io.admin-shell.asset.<modification>.v1`.

This class is not part of the metamodel.
h|Inherits from 3+|xref:EventData[EventData]
h|semanticId 3+|`\https://admin-shell.io/aas/API/DataTypes/AssetEventData/3/3`
h|Attribute h|Explanation h|Type h|Card.
e|globalAssetIds a|_globalAssetId_ of the asset; exactly one entry |link:{mm}/spec-metamodel/datatypes.html#Identifier[Identifier] |1..*
e|assetAdministrationShells a|Content _Normal_ only: ModelReferences to the Asset Administration Shells linked to the asset after the modification; for _deleted_ events, before the modification |link:{mm}/spec-metamodel/referencing.html#Reference[Reference] |0..*
|===

====
Note: `globalAssetIds` is a list in all classes to allow a uniform JSON path for filtering.
====

[#eventing-data-schemas]
=== Data Schemas

The `dataschema` of an event identifies the class and the Content of its data:

....
https://admin-shell.io/aas/API/Events/<class name>/<Content>/3/3
....

`<class name>` is the name of the event data class and `<Content>` is `Normal` or `Reference`, e.g. `\https://admin-shell.io/aas/API/Events/SubmodelElementEventData/Reference/3/3`.

A service may provide an event with Content _Reference_ where Content _Normal_ was requested, e.g. if the event exceeds a size limit.
Clients shall therefore evaluate the `dataschema` of each event.

The following event reports a new value of the Property `temperature` in the SubmodelElementCollection `Measurements` with Content _Normal_.
Examples for all event types are given in Annex xref:annex/eventing-examples.adoc[Eventing Examples].

[source,json]
----
{
  "specversion": "1.0",
  "id": "0192a3f5-1a03-7003-b2d8-6e1f4c9a0b27",
  "type": "io.admin-shell.submodelelement.updated.v1",
  "source": "https://aas.example.com/submodels/aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vNDIxMF8wODAyXzYxNTJfNTQyMQ/submodel-elements",
  "subject": "Measurements.temperature",
  "time": "2026-09-29T10:05:12.345678Z",
  "datacontenttype": "application/json",
  "dataschema": "https://admin-shell.io/aas/API/Events/SubmodelElementEventData/Normal/3/3",
  "data": {
    "submodel": {
      "type": "ModelReference",
      "referredSemanticId": {
        "type": "ExternalReference",
        "keys": [ { "type": "GlobalReference", "value": "https://example.com/semantics/OperationalData/1/0" } ]
      },
      "keys": [ { "type": "Submodel", "value": "https://example.com/ids/sm/4210_0802_6152_5421" } ]
    },
    "globalAssetIds": [ "https://example.com/ids/asset/7600_5912_3951_6917" ],
    "submodelElement": {
      "modelType": "Property",
      "idShort": "temperature",
      "semanticId": {
        "type": "ExternalReference",
        "keys": [ { "type": "GlobalReference", "value": "https://example.com/ids/cd/temperature" } ]
      },
      "valueType": "xs:double",
      "value": "21.4"
    }
  }
}
----

[#eventing-modifications]
== Modifications and Events

[#eventing-modifications-general]
=== General

A modification is a change of the content provided by a service that becomes visible to clients as a whole, e.g. the result of a successful API operation.
The following rules apply:

. Every modification shall result in the events defined in this clause, regardless of whether it is caused by an API operation, an import of an AASX package or environment, or the service itself.
Unsuccessful operations and operations without any change of the content result in no events.
. A modification of an Asset Administration Shell, Submodel, or Concept Description results in exactly one event for this Identifiable, of type `created`, `updated`, or `deleted`.
. A modification of SubmodelElements additionally results in SubmodelElement events according to <<eventing-sme-events>>.
The creation or deletion of a Submodel results in no SubmodelElement events.
. A modification of the link between an asset and Asset Administration Shells additionally results in asset events according to <<eventing-asset-events>>.
. Events concerning the same Identifiable shall be provided in the order of the modifications; for SubmodelElement events this is the Submodel, for asset events the asset.
Within one modification, SubmodelElement events precede the Submodel event, and the AAS event precedes the asset events.

<<table-eventing-operations>> lists the events resulting from the operations of this specification.

[[table-eventing-operations]]
.Events resulting from operations
[%autowidth,width="100%",cols="45%,55%",options="header",]
|===
|Operation |Events (without prefix `io.admin-shell.` and suffix `.v1`)
|xref:specification/interfaces.adoc#PostAssetAdministrationShell[PostAssetAdministrationShell], xref:specification/interfaces.adoc#PutAssetAdministrationShellById[PutAssetAdministrationShellById], xref:specification/interfaces.adoc#PutAssetAdministrationShell[PutAssetAdministrationShell], xref:specification/interfaces.adoc#PutAssetInformation[PutAssetInformation], xref:specification/interfaces.adoc#PutThumbnail[PutThumbnail], xref:specification/interfaces.adoc#DeleteThumbnail[DeleteThumbnail], xref:specification/interfaces.adoc#PostSubmodelReference[PostSubmodelReference], xref:specification/interfaces.adoc#DeleteSubmodelReference[DeleteSubmodelReference], xref:specification/interfaces.adoc#DeleteAssetAdministrationShellById[DeleteAssetAdministrationShellById] |`+aas.*+`; `+asset.*+` if the _globalAssetId_ is set, changed, or removed
|xref:specification/interfaces.adoc#PostSubmodel[PostSubmodel], xref:specification/interfaces.adoc#DeleteSubmodelById[DeleteSubmodelById] |`submodel.created`, `submodel.deleted`
|xref:specification/interfaces.adoc#PutSubmodelById[PutSubmodelById], xref:specification/interfaces.adoc#PutSubmodel[PutSubmodel], xref:specification/interfaces.adoc#PatchSubmodelById[PatchSubmodelById], xref:specification/interfaces.adoc#PatchSubmodel[PatchSubmodel] |`submodel.created`, or `submodelelement.*` and `submodel.updated`
|xref:specification/interfaces.adoc#PostSubmodelElement[PostSubmodelElement], xref:specification/interfaces.adoc#PostSubmodelElementByPath[PostSubmodelElementByPath], xref:specification/interfaces.adoc#PutSubmodelElementByPath[PutSubmodelElementByPath], xref:specification/interfaces.adoc#PatchSubmodelElementByPath[PatchSubmodelElementByPath], xref:specification/interfaces.adoc#PatchSubmodelElementValueByPath[PatchSubmodelElementValueByPath], xref:specification/interfaces.adoc#PutFileByPath[PutFileByPath], xref:specification/interfaces.adoc#DeleteFileByPath[DeleteFileByPath], xref:specification/interfaces.adoc#DeleteSubmodelElementByPath[DeleteSubmodelElementByPath] |`submodelelement.*` and `submodel.updated`
|xref:specification/interfaces.adoc#PostConceptDescription[PostConceptDescription], xref:specification/interfaces.adoc#PutConceptDescriptionById[PutConceptDescriptionById], xref:specification/interfaces.adoc#DeleteConceptDescriptionById[DeleteConceptDescriptionById] |`conceptdescription.*`
|xref:specification/interfaces.adoc#PostAllAssetLinksById[PostAllAssetLinksById], xref:specification/interfaces.adoc#DeleteAllAssetLinksById[DeleteAllAssetLinksById] |`asset.*` if an AssetLink with name `globalAssetId` is added or removed
|===

[#eventing-sme-events]
=== SubmodelElement Events

SubmodelElement events are determined by comparing the Submodel before and after the modification.
Child elements, i.e. the elements in `value` of SubmodelElementCollections and SubmodelElementLists, in `statements` of Entities, and in `annotations` of AnnotatedRelationshipElements, are SubmodelElements of their own and not attributes of their parent.
The following rules apply:

. A SubmodelElement with a modified attribute results in one `submodelelement.updated` event.
A modification of a child element does not result in an event for its parent.
. An added SubmodelElement results in one `submodelelement.created` event, a removed SubmodelElement in one `submodelelement.deleted` event.
The child elements of an added or removed SubmodelElement result in no events.
. A modified `idShort` results in `submodelelement.deleted` for the previous and `submodelelement.created` for the new idShortPath.
. If a modification changes the index of existing elements of a SubmodelElementList, it results in one `submodelelement.updated` event for the SubmodelElementList instead of events for its elements.
Elements added to or removed from the end of a SubmodelElementList result in `submodelelement.created` or `submodelelement.deleted` events.
. SubmodelElement events of one modification are ordered depth-first according to the position of the SubmodelElements in the Submodel.

.Examples for SubmodelElement events
[%autowidth,width="100%",cols="50%,50%",options="header",]
|===
|Modification |SubmodelElement events
|Value of `Measurements.temperature` modified |`updated` for `Measurements.temperature`
|`description` of `Measurements` and value of `Measurements.temperature` modified |`updated` for `Measurements` and for `Measurements.temperature`
|SubmodelElementCollection `Maintenance` with two Properties added |`created` for `Maintenance`
|`idShort` of `Measurements.temp` modified to `temperature` |`deleted` for `Measurements.temp`, `created` for `Measurements.temperature`
|Element appended to SubmodelElementList `Records` with three elements |`created` for `Records[3]`
|Element inserted at index 0 of SubmodelElementList `Records` |`updated` for `Records`
|Only `description` of the Submodel modified |none
|===

<<fig-eventing-seq-sme-update>> shows the events resulting from a value update and their retrieval with both Contents.

.Events of a SubmodelElement value update
[[fig-eventing-seq-sme-update]]
[plantuml, eventing-seq-submodel-element-update, svg]
....
include::partial$diagrams/eventing-seq-submodel-element-update.puml[]
....

[#eventing-asset-events]
=== Asset Events

An Asset Administration Shell is linked to the asset with the _globalAssetId_ `X` if it is provided by the service and the attribute `globalAssetId` of its link:{mm}/spec-metamodel/core.html#AssetInformation[AssetInformation] has the value `X`, or if an xref:specification/interfaces-payload.adoc#AssetLink[AssetLink] with name `globalAssetId` and value `X` is registered for it.
A modification that changes the set of Asset Administration Shells linked to `X` results in one asset event for `X`, as shown in <<fig-eventing-asset-link-states>>:

* `asset.created` if the set was empty before the modification,
* `asset.deleted` if the set is empty after the modification,
* `asset.updated` otherwise.

A modification of the _globalAssetId_ of an Asset Administration Shell from `A` to `B` results in asset events for `A` and for `B`.

.Asset events
[[fig-eventing-asset-link-states]]
[plantuml, eventing-asset-link-states, svg]
....
include::partial$diagrams/eventing-asset-link-states.puml[]
....

[#eventing-profiles]
== Event Profiles

An event profile defines additional event types for a Submodel template, e.g. an event type for a new record in a Submodel with Product Change Notifications.
An event profile shall define

. the event types in the form `<prefix>.<object>.<modification>.v<major>`, where `<prefix>` is `io.admin-shell` for profiles defined by the IDTA and a reverse domain name of the defining organization otherwise,
. the SubmodelElement events of <<eventing-sme-events>> that result in a profile event,
. `source` and `subject` according to <<eventing-source-subject>>,
. the event data for Content _Normal_ and _Reference_, composed of classes of Part 1 xref:bibliography.adoc#bib1[[1\]] and this specification,
. the `dataschema` values.

Profile events are provided in addition to the events of <<eventing-modifications>>, and precede the Submodel event of the same modification.

[#eventing-interface]
== Event Interface

[#eventing-interface-operations]
=== Operation GetAllEvents

[.table-with-appendix-table]
[width=100%,cols="25%,35%,10%,20%,10%"]
|===
h|Operation Name 4+e|[[GetAllEvents]]GetAllEvents
h|Explanation 4+a|Returns the events provided by the service.
Different input parameters are evaluated with AND semantics; the values of one input parameter with OR semantics.
h|semanticId 4+|`\https://admin-shell.io/aas/API/GetAllEvents/3/3`

h|Name h|Description h|Mand. h|Type h|Card.
5+h|Input Parameter
e|type a|Return events of the given types |no |string |0..*
e|id a|Return events of the given Identifiables, i.e. AAS, Submodel, and Concept Description events with this `subject`, and SubmodelElement and profile events of the Submodel with this identifier |no |link:{mm}/spec-metamodel/datatypes.html#Identifier[Identifier] |0..*
e|idShortPath a|Return SubmodelElement and profile events whose `subject` is the given idShortPath or starts with it followed by `.` or `[`; requires exactly one `id` |no |string |0..1
e|globalAssetId a|Return events whose `globalAssetIds` contain the given value |no |link:{mm}/spec-metamodel/datatypes.html#Identifier[Identifier] |0..*
e|semanticId a|Return Submodel and SubmodelElement events of objects with the given _semanticId_ or _supplementalSemanticId_ |no |link:{mm}/spec-metamodel/referencing.html#Reference[Reference] |0..*
e|submodelSemanticId a|Return Submodel, SubmodelElement, and profile events of Submodels with the given _semanticId_ or _supplementalSemanticId_ |no |link:{mm}/spec-metamodel/referencing.html#Reference[Reference] |0..*
e|timeFrom a|Return events with a `time` at or after the given date |no |link:{mm}/spec-metamodel/datatypes.html#DateTimeUtc[DateTimeUtc] |0..1
e|serializationModifier a|Content of the event data; _Normal_ or _Reference_ |yes |xref:specification/interfaces-operation-parameters.adoc#SerializationModifier[SerializationModifier] |1
e|limit |The maximum size of the result set |no |nonNegativeInteger |0..1
e|cursor |The position from which to resume a result listing |no |string |0..1
5+h|Output Parameter
e|statusCode |Status code |yes |xref:specification/interfaces-payload.adoc#StatusCode[StatusCode] |1
e|payload |List of events |no |xref:Event[Event] |0..*
|===

The following rules apply:

. Filters are evaluated on the event independent of the requested Content.
. The events are returned in a server-defined order that fulfills the ordering rules of <<eventing-modifications-general>> and does not change between requests.
. The result of GetAllEvents is continued by events of later modifications.
In deviation from xref:http-rest-api/http-rest-api.adoc#pagination[Pagination], the server shall therefore also return a cursor with the last page; a request with this cursor returns the events provided afterwards.
. A server may remove events after a server-defined period.
If a cursor refers to removed events, the server shall respond with the status code _ClientErrorResourceNotFound_.
. Access to events is subject to Part 4 xref:bibliography.adoc#bib3[[3\]]; an event shall only be returned if the client may read the complete event data.

[#eventing-interface-http]
=== HTTP/REST Mapping

[%autowidth,width="100%",cols="31%,10%,23%,36%"]
|===
h|Operation Name h|HTTP Verb h|REST-Path h|Comment (e.g. optional query parameters)
|GetAllEvents |GET |/events a|content-suffix: $reference

?type=, ?id=, ?idShortPath=, ?globalAssetId=, ?semanticId=, ?submodelSemanticId=, ?timeFrom=, Pagination

id and globalAssetId are base64url-encoded; semanticId and submodelSemanticId are JSON-serialized and base64url-encoded; idShortPath is URL-encoded; lists are comma-separated
|===

The response is a Result object according to xref:http-rest-api/http-rest-api.adoc#pagination[Pagination] whose `result` contains the events.

[#eventing-related-concepts]
== Relation to Other Concepts

[#eventing-related-recent-changes]
=== Recent Changes

The operations
xref:specification/interfaces.adoc#GetAllAssetAdministrationShellsRecentChanges[GetAllAssetAdministrationShellsRecentChanges],
xref:specification/interfaces.adoc#GetAllSubmodelsRecentChanges[GetAllSubmodelsRecentChanges], and
xref:specification/interfaces.adoc#GetAllConceptDescriptionsRecentChanges[GetAllConceptDescriptionsRecentChanges]
return Identifiables created or updated after a given point in time, based on their current state.
They report neither deletions nor modified SubmodelElements, and they return an Identifiable once, regardless of the number of its modifications.
Events report every modification, including deletions and modifications of SubmodelElements.

[#eventing-related-history]
=== Versions at a Point in Time

The operations
xref:specification/interfaces.adoc#GetAssetAdministrationShellVersionByIdAndDate[GetAssetAdministrationShellVersionByIdAndDate] and
xref:specification/interfaces.adoc#GetSubmodelVersionByIdAndDate[GetSubmodelVersionByIdAndDate]
return an Identifiable as it was at a given point in time.
Called with the `time` of an event with Content _Reference_, they return the state described by the event.

[#eventing-related-event-element]
=== EventElement and EventPayload

Part 1 xref:bibliography.adoc#bib1[[1\]] defines the classes
link:{mm}/spec-metamodel/submodel-elements.html#EventElement[EventElement],
link:{mm}/spec-metamodel/submodel-elements.html#BasicEventElement[BasicEventElement], and
link:{mm}/spec-metamodel/submodel-elements.html#EventPayload[EventPayload].
They describe events that are declared as part of the model content and refer to a source EventElement.
The events of this chapter result from modifications of the content provided by a service, independent of the model content, and do not use these classes.

[#eventing-related-protocols]
=== Other Protocols

This chapter defines the retrieval of events via _GetAllEvents_.
Events can be transmitted via other protocols, e.g. MQTT, Kafka, or AMQP, using the CloudEvents protocol bindings xref:bibliography.adoc#bib18[[18\]]; such mappings are not defined by this specification.

[#eventing-query-language]
== Filtering with the AAS Query Language (informative)

[IMPORTANT]
====
*This clause is a proposal and not part of this specification.*
The normative filters are the input parameters of xref:GetAllEvents[GetAllEvents].
====

The xref:query-language.adoc[AAS Query Language] could be extended by a root element `$event` for FieldIdentifiers, e.g. `$event#type`, `$event#subject`, `$event#time`, `$event#globalAssetIds[]`, `$event#semanticId`, and `$event#submodelSemanticId`.
This would allow filters that the input parameters cannot express, e.g. a negation:

[source,json]
----
{
  "$condition": {
    "$and": [
      { "$starts-with": [ { "$field": "$event#type" }, { "$strVal": "io.admin-shell.submodelelement." } ] },
      { "$not": { "$eq": [ { "$field": "$event#globalAssetIds[]" }, { "$strVal": "https://example.com/ids/asset/0000" } ] } }
    ]
  }
}
----

This requires changes of the grammar and JSON Schema shared with Part 4 xref:bibliography.adoc#bib3[[3\]], see xref:query-language.adoc#formula-grammar-sot[Single source of truth for the formula grammar and JSON Schema].
